sonar.projectKey=founderlink-microservices
sonar.projectName=FounderLink Microservices
sonar.sourceEncoding=UTF-8

sonar.sources=\
  api-gateway/src/main/java,\
  auth-service/src/main/java,\
  config-server/src/main/java,\
  eureka-server/src/main/java,\
  investment-service/src/main/java,\
  messaging-service/src/main/java,\
  notification-service/src/main/java,\
  startup-service/src/main/java,\
  team-service/src/main/java,\
  user-service/src/main/java

sonar.tests=\
  api-gateway/src/test/java,\
  auth-service/src/test/java,\
  config-server/src/test/java,\
  eureka-server/src/test/java,\
  investment-service/src/test/java,\
  messaging-service/src/test/java,\
  notification-service/src/test/java,\
  startup-service/src/test/java,\
  team-service/src/test/java,\
  user-service/src/test/java

sonar.java.binaries=**/target/classes
sonar.java.test.binaries=**/target/test-classes
sonar.junit.reportPaths=**/target/surefire-reports

sonar.exclusions=**/logs/**,**/target/**,**/mvnw,**/mvnw.cmd
